### ISSUE TITLE
Resolve cloudpebble compile error about menu icon size

### ISSUE THREAD

**Issue by zo0o0ot** [zo0o0ot/AppletonPebble#14]
```
Setting top to                           : /tmp/tmpsOOeTj 
Setting out to                           : /tmp/tmpsOOeTj/build 
WARNING: enableMultiJS is not enabled for this project. message_keys.json will not be included in your project unless you add it to your pebble-js-app.js file. 
Found Pebble SDK for basalt in:          : /app/sdk3/pebble/basalt 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for aplite in:          : /app/sdk3/pebble/aplite 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
'configure' finished successfully (0.127s)
Waf: Entering directory `/tmp/tmpsOOeTj/build'
menuIcon resource 'IMAGE_MENU_ICON' exceeds the maximum allowed dimensions of (25, 25)
```

I didn't have an icon attached, so this was confusing.

I attached a menu icon image, but it didn't help.

I found these forum conversations about it:
https://forums.pebble.com/t/simple-default-pebblejs-project-does-not-compile/24571/4
https://forums.pebble.com/t/building-app-fails-due-to-nonexistent-image-menu-icon/24609

Hoping to find a fix. It will help with issue #13

**Comment by zo0o0ot** [comment]
Uploaded icon.  Also, you need to update the reference in the settings.
![image](https://cloud.githubusercontent.com/assets/876146/19216056/80d1ba5e-8d74-11e6-95ad-aefaf4e4e7a8.png)

Updating for pebble time 2 fails, but pebble time round support can be added.

**Comment by SonnyJim** [comment]
I'm still getting this error:

Setting top to                           : /tmp/tmpTa3Jll 
Setting out to                           : /tmp/tmpTa3Jll/build 
Checking for program webpack             : /app/node_modules/.bin/webpack 
WARNING: enableMultiJS is not enabled for this project. message_keys.json will not be included in your project unless you add it to your pebble-js-app.js file. 
Found Pebble SDK for emery in:           : /app/sdk3/pebble/emery 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for diorite in:         : /app/sdk3/pebble/diorite 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for chalk in:           : /app/sdk3/pebble/chalk 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for basalt in:          : /app/sdk3/pebble/basalt 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for aplite in:          : /app/sdk3/pebble/aplite 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
'configure' finished successfully (0.209s)
Waf: Entering directory `/tmp/tmpTa3Jll/build'
menuIcon resource 'IMAGE_MENU_ICON' exceeds the maximum allowed dimensions of (25, 25)
